### ISSUE TITLE
Add exclusion rule to validate-artifacts.yml

### ISSUE THREAD

**Issue by yada** [microcks/community-mocks#5]
### Reason/Context

Related to .github replication workflow, see: https://github.com/microcks/.github/issues/16

### Description

Missing exclusion rule in validate-artifacts workflow

### Implementation ideas

Add
```
on:
  push:
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - 'LICENSE'
      - 'README*'
      - 'CODE_OF_CONDUCT*'
  pull_request:
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - 'LICENSE'
      - 'README*'
      - 'CODE_OF_CONDUCT*'
```
